In [25]:
from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd
from sklearn import metrics

In [26]:
from sklearn.metrics import confusion_matrix,classification_report

In [27]:
iris=load_iris()
x=iris.data
y=iris.target

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4)
print("size of training data and its label",x_train.shape,y_train.shape)
print("size of testing data and its label",x_test.shape,y_test.shape)

size of training data and its label (90, 4) (90,)
size of testing data and its label (60, 4) (60,)


In [29]:
for i in range(len(iris.target_names)):
    print("Label",i,"-",str(iris.target_names[i]))

Label 0 - setosa
Label 1 - versicolor
Label 2 - virginica


In [30]:
classifier=KNeighborsClassifier(n_neighbors=1)

In [31]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [32]:
y_predict=classifier.predict(x_test)

In [35]:
for r in range(len(x_test)):
    print("sample",str(x_test[r]),"Actual_label",str(y_test[r]),"predicted_label",str(y_predict[r]))
print("classification Accuracy:",classifier.score(x_test,y_test))

sample [4.8 3.1 1.6 0.2] Actual_label 0 predicted_label 0
sample [6.5 3.  5.8 2.2] Actual_label 2 predicted_label 2
sample [6.7 3.3 5.7 2.5] Actual_label 2 predicted_label 2
sample [5.5 4.2 1.4 0.2] Actual_label 0 predicted_label 0
sample [5.6 2.9 3.6 1.3] Actual_label 1 predicted_label 1
sample [6.8 2.8 4.8 1.4] Actual_label 1 predicted_label 1
sample [5.8 2.6 4.  1.2] Actual_label 1 predicted_label 1
sample [4.8 3.  1.4 0.1] Actual_label 0 predicted_label 0
sample [7.7 2.8 6.7 2. ] Actual_label 2 predicted_label 2
sample [5.7 2.8 4.1 1.3] Actual_label 1 predicted_label 1
sample [5.  3.3 1.4 0.2] Actual_label 0 predicted_label 0
sample [6.5 3.  5.5 1.8] Actual_label 2 predicted_label 2
sample [5.5 2.3 4.  1.3] Actual_label 1 predicted_label 1
sample [6.8 3.  5.5 2.1] Actual_label 2 predicted_label 2
sample [4.5 2.3 1.3 0.3] Actual_label 0 predicted_label 0
sample [5.1 3.8 1.5 0.3] Actual_label 0 predicted_label 0
sample [6.7 3.1 5.6 2.4] Actual_label 2 predicted_label 2
sample [6.3 2.

In [34]:
print("confusion Matrix")
print(confusion_matrix(y_test,y_predict))
print("accuracy metrics")
print(classification_report(y_test,y_predict))
print("accuracy_score",metrics.accuracy_score(y_test,y_predict))


confusion Matrix
[[20  0  0]
 [ 0 17  2]
 [ 0  2 19]]
accuracy metrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       0.89      0.89      0.89        19
           2       0.90      0.90      0.90        21

    accuracy                           0.93        60
   macro avg       0.93      0.93      0.93        60
weighted avg       0.93      0.93      0.93        60

accuracy_score 0.9333333333333333
